version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  be-node-express:
    build: ./be-node-express
    container_name: todo-be-node-dev
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-network

  be-nestjs:
    build: ./be-nestjs
    container_name: todo-be-nest-dev
    restart: always
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-network

  be-fastapi:
    build: ./be-fastapi
    container_name: todo-be-fastapi-dev
    restart: always
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-network

  fe-vite:
    build: ./fe-vite
    container_name: todo-fe-vite-dev
    restart: always
    ports:
      - "5173:5173"
    networks:
      - todo-network

  fe-nextjs:
    build: ./fe-nextjs
    container_name: todo-fe-nextjs-dev
    restart: always
    ports:
      - "3000:3000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  pgdata_dev:
